// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs8HCgp7fgrRSeMucrN9EXwqkoWrJpc2M',
    appId: '1:211519231124:android:30c61336e2b616c7c5d081',
    messagingSenderId: '211519231124',
    projectId: 'lumiconte-1f086',
    storageBucket: 'lumiconte-1f086.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyu29G40E_wI41us6EDI1tIShlaANB5TU',
    appId: '1:211519231124:ios:0988cea71259af64c5d081',
    messagingSenderId: '211519231124',
    projectId: 'lumiconte-1f086',
    storageBucket: 'lumiconte-1f086.firebasestorage.app',
    androidClientId: '211519231124-7vi4lcakkklcqgarc8ljc0d08rtfuqcq.apps.googleusercontent.com',
    iosClientId: '211519231124-fbe0n7pvbfsieub9njcp3ehb9v3n0roi.apps.googleusercontent.com',
    iosBundleId: 'com.example.lumiconte',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3i5WmmzkGNfKsC1bbxmbquPEqbUAId0E',
    appId: '1:211519231124:web:c53346cdd14a0673c5d081',
    messagingSenderId: '211519231124',
    projectId: 'lumiconte-1f086',
    authDomain: 'lumiconte-1f086.firebaseapp.com',
    storageBucket: 'lumiconte-1f086.firebasestorage.app',
    measurementId: 'G-ZBGR4PY246',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyu29G40E_wI41us6EDI1tIShlaANB5TU',
    appId: '1:211519231124:ios:0988cea71259af64c5d081',
    messagingSenderId: '211519231124',
    projectId: 'lumiconte-1f086',
    storageBucket: 'lumiconte-1f086.firebasestorage.app',
    androidClientId: '211519231124-7vi4lcakkklcqgarc8ljc0d08rtfuqcq.apps.googleusercontent.com',
    iosClientId: '211519231124-fbe0n7pvbfsieub9njcp3ehb9v3n0roi.apps.googleusercontent.com',
    iosBundleId: 'com.example.lumiconte',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3i5WmmzkGNfKsC1bbxmbquPEqbUAId0E',
    appId: '1:211519231124:web:56d1d8383dd46826c5d081',
    messagingSenderId: '211519231124',
    projectId: 'lumiconte-1f086',
    authDomain: 'lumiconte-1f086.firebaseapp.com',
    storageBucket: 'lumiconte-1f086.firebasestorage.app',
    measurementId: 'G-HE6EYSKDSK',
  );
}
